# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_users_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField(auto_now=True)),
                ('date_to', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email_address',
        ),
        migrations.AddField(
            model_name='trips',
            name='user_id',
            field=models.ManyToManyField(related_name='trips', to='first_app.Users'),
        ),
    ]
