# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20171121_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trips',
            name='user_joining',
            field=models.ManyToManyField(related_name='user_joiners', to='first_app.Users'),
        ),
        migrations.AddField(
            model_name='trips',
            name='user_trip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='first_app.Users'),
            preserve_default=False,
        ),
    ]
